# Configure status bar
set -g status-position top
set -g status-justify left
set -g status-style 'fg=#9e6a03 bg=#21262d'
set -g status-right ''

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Start window and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1

# Renumber windows
set-option -g renumber-windows on

#Neovim: `focus-events` is not enabled. |'autoread'| may not work.
set-option -g focus-events on

# Reload configuration
bind r source-file ~/.tmux.conf
